language: php

php:
  - 5.3
  - 5.4

before_script:
  - pear config-set audo_discover 1
  - pear channel-discover pear.phpspec.net
  - pear install phpspec/PHPSpec

script: phpspec src/spec --bootstrap src/spec/bootstrap.php
