language: php

php:
  - 5.4
  - 5.5

before_script:
  # UOPZ
  - git clone https://github.com/krakjoe/uopz.git
  - sh -c "cd uopz && phpize && ./configure && make && sudo make install"
  - echo "extension=uopz.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`

  # Composer
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev

script: vendor/bin/phpunit test/
