language: php

php:
  - 5.3
  - 5.4

before_script:
  # Runkit
  - git clone https://github.com/zenovich/runkit.git
  - sh -c "cd runkit && phpize && ./configure && make && sudo make install"
  - echo "extension=runkit.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`

  # PHPSpec
  - git clone https://github.com/phpspec/phpspec.git
  - sh -c "cd phpspec && php vendor/vendors.php"

script: php phpspec/scripts/phpspec.php src/spec --bootstrap src/spec/bootstrap.php
