language: php

php:
  - 5.3
  - 5.4

before_script:
  # Runkit
  - git clone https://github.com/zenovich/runkit.git
  - sh -c "cd runkit && phpize && ./configure && make && sudo make install"
  - echo "extension=runkit.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`

  # Composer
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev

script: php vendor/bin/phpspec.php src/spec
